### ISSUE TITLE
Media in media browser listed but empty

### ISSUE THREAD

**Issue by loadamasta** [dermotduffy/hass-motioneye#135]
custom_component v0.0.17
home assistant os 6.5, core-2021.10.5
motioneye add-on 0.15.1

## Describe the bug

Using this custom component alongside with the add-on, configured as described here (http://localhost:28765): in ha media browser the files recorded by motioneye add-on are listed but empty respectively cannot be found and be shown. Perhaps, the provided links are wrong.

The link provided by the motioneye add-on is "http://IP:8123/api/hassio_ingress/iDB5QusbLldmMd9prHTLDmQPbjUuEG_IExHsFrVtOzo/picture/1/preview/2021-10-15/15-13-16.jpg?_username=admin&_signature=4a6d3febaeee74b2be907b2bd033be06fb5d7073" while the link to the same picture offered by ha media browser is "http://localhost:28765/picture/1/download/2021-10-15/15-13-16.jpg?_username=admin&_signature=4fdbe4d26c37c2f0720a82e41af2f4d6beb47e73". 

![Medien-Browser - Home Assistant 2021-10-16 11-13-01](https://user-images.githubusercontent.com/66960049/137582564-8aadc9a0-777e-4048-9e87-474f7d347018.png)

**Comment by dermotduffy** [comment]
Not sure there's a great story here. The issue is that the integration itself needs the localhost address to access the backend, but that isn't going to work for your browser . The real fix is to use the motionEye integration that I'm moving into the core HA (i.e. not a custom integration), [all the PRs are prepared](https://github.com/home-assistant/core/pulls?q=is%3Apr+is%3Aopen+motioneye) that equalize the functionality, but the codereview delay is high -- I'm just waiting. [This is the PR that will add media browser](https://github.com/home-assistant/core/pull/53436) to Core.

The reason that's the real fix is that the Core side already includes automated discovery of the addon and the right URL to it, so the problem highlighted here doesn't exist there.

Other options besides 'wait' include:
 - You could run motionEye not as an addon, then the media browser would work fine.
 - We could look to backport the addon discovery from core to this repo. Personally, I'd really like to avoid making changes to this custom repository, as it's only incurring additional debt until the move is complete -- but if you wanted to prepare a PR it'd be most welcome.

In any case, we should update the documentation to make it clear that the media browser will not work in this configuration for this reason.

**Comment by loadamasta** [comment]
I can understand not to change code of the custom component. Waiting is always an option and no problem ;)  Thank you very much for your efforts.

**Comment by dermotduffy** [comment]
Added a note to the README that for now this is working as intended. Thanks for the report and patience on the migration!
