### ISSUE TITLE
Motion events to binary sensor

### ISSUE THREAD

**Issue by roger-** [dermotduffy/hass-motioneye#40]
Might be nice to directly expose motion/file events as binary sensors.

**Comment by dermotduffy** [comment]
Thanks for the feedback!

Considered that, but went with [events](https://github.com/dermotduffy/hass-motioneye#events) instead. If it's a binary sensor, we have fake state at when the motion detection ends (i.e. when the binary sensor flips back to False, e.g. wait an arbitrary 30 seconds). Rather than fake that state, events seemed like a more natural fit.

Are there usecases where a binary sensor would work, but events will not?

**Comment by roger-** [comment]
Good point, but if you consider the motion to be a point in time with no duration then it's not unreasonable to have the binary sensor toggle after some very short period.

Haven't used events before but my main interest is in having it all logged automatically by hass (like some of my other cameras). 

Great work BTW!

**Comment by roger-** [comment]
Much appreciated, thanks!

**Comment by dermotduffy** [comment]
No problem. It will be in the next release.

**Comment by dermotduffy** [comment]
This is now released.
