### ISSUE TITLE
Webhooks not triggering reliably 

### ISSUE THREAD

**Issue by broyuken** [dermotduffy/hass-motioneye#57]
## Version of the custom_component

v0.0.17

## Describe the bug

Motion webhooks are not being sent all the time. I can walk into a room and watch the motioneye camera show me in lovelace, but the motion sensor does not turn on. I know motion detection is working because motioneye records me walking in, it just doesn't update the binary sensor. Testing the webhook, I can enter the url into my browser and the sensor triggers so the communication between the two works fine. It just seems that sometimes the webhook doesn't get sent.

**Comment by dermotduffy** [comment]
If the webhook is failing to be called, that is an issue with [motionEye itself](https://github.com/ccrisan/motioneye) rather than this integration. This integration is only as good as motionEye's ability to call the webhook.

One way to be sure would be to set the webhook URL to something else where you can check the logs of the call. If the correct log entries get created reliably, then perhaps the problem is on the integration side and we could debug further. If not, the problem is on the motionEye side and you should file an issue there.

**Comment by dermotduffy** [comment]
As per your update on https://github.com/dermotduffy/hass-motioneye/issues/55 , I think you managed to get this resolved. If I'm mistaken, and you think there's more to do here, please re-open with new state. Thanks!
